name: hyperopt
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '5 5 * * *'

jobs:
  build:
    name: hyperopt ci
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java_version: ['17']

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          architecture: x64

      - name: Tests
        run: |
          curl -fsSL get.nextflow.io | bash
          export NXF_EDGE=1
          ./nextflow -self-update
          ./nextflow run . -profile wave
        env:
          NXF_ANSI_LOG: false
          NXF_TRACE: nextflow.processor

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nextflow-logs-${{ matrix.java_version }}
          path: |
            .nextflow.*
